sudo: required
services:
  - docker

before_install:
  - docker build -t poptanai/docker-react -f Dockerfile.dev .

script:
  - docker run -t poptanai/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: : "ap-southeast-1"
  application: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-874704647857"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
